reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:create, :new]
  resource :sessions, only: [:create, :new, :destroy]

  resources :subs, except:[:destroy] do
    resources :posts, only: [:new]
  end

  resources :posts, only: [:create, :edit, :destroy, :update, :show, :new]

  
end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :bigint           not null
#  author_id  :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
  validates :title, presence: true 
  validates :sub, :author, presence: true
  belongs_to :sub
  belongs_to :author,
    class_name: :User 


end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Sub < ApplicationRecord

  validates :title, presence: true, uniqueness: true, length: {minimum: 5}
  validates :moderator, presence: true 
  belongs_to :moderator,
    class_name: :User 

  has_many :posts,
    dependent: :destroy 


end

reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
    validates :username, :session_token, presence: true, uniqueness: true 
    validates :password_digest, presence: true 
    validates :password, length: {minimum: 6}, allow_nil: true 


    before_validation :ensure_session_token
    attr_reader :password 

    has_many :subs,
        foreign_key: :moderator_id,
        inverse_of: :moderator,
        dependent: :destroy 
    
    has_many :posts,
        foreign_key: :author_id,
        inverse_of: :author,
        dependent: :destroy

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)

        user&&user.is_password?(password) ? user : nil 
    end


    def password=(password)
        @password=password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        passwordo = BCrypt::Password.new(self.password_digest)
        passwordo.is_password?(password)
    end

    def reset_session_token!
        self.session_token = generate_unique_token
        self.save!
        self.session_token 
    end
    

    private
    def generate_unique_token 
        loop do 
            token = SecureRandom::urlsafe_base64(16)
            return token unless User.exists?(session_token: token)
        end
    end

    def ensure_session_token 
        self.session_token ||=generate_unique_token
    end


end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def current_user
        return nil unless session[:session_token]
        @current_user ||=User.find_by(session_token:session[:session_token])
    end

    def logged_in?
        !!current_user 
    end

    def logout! 
        current_user.reset_session_token!
        session[:session_token]=nil 
        @current_user = nil 
    end

    def required_logged_in 
        redirect_to new_sessions_url unless logged_in? 
    end



end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user =User.new.decorate 
    end

    def create
        @user=User.find_by_credentials(params[:user][:username],params[:user][:password])
        
        if @user 
            login!(@user)
            flash[:notices]=['Sucessful Login']
            redirect_to subs_url 
        else
            flash.now[:errors]=@user.errors.full_messages
            @user=User.new(username: params[:user][:username]).decorate 
            render :new 
        end

    end

    def destroy 
        logout!
        flash[:notices]=['Successful Logout']
        redirect_to new_sessions_url
    end

    def user_params 
        params.require(:user).permit(:username, :password)
    end
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    def new 
        @sub = Sub.new.decorate 
        render :new 
    end
    def create 
        @sub = Sub.new(sub_params)
        @sub.moderator_id = current_user.id 
        if @sub.save 
            flash[:notices] = ['Sub created']
            redirect_to sub_url(@sub)
        else 
            flash.now[:errors]=@sub.errors.full_messages 
            render :new 
        end
    end

    def show 
        @sub = Sub.find_by(id: params[:id])
        render :show
    end
    def index 
        @subs= Sub.all 
        render :index 
    end

    def edit
        @sub = Sub.find_by(id: params[:id]).decorate
        render :edit 
    end
    def update 
        @sub = Sub.find_by(id: params[:id])
        if @sub.update(sub_params)
            flash[:notices]=["Successful Update"]
            redirect_to sub_url(@sub)
        else
            flash.now[:errors]=@sub.errors.full_messages 
            render :edit 
        end
    end

    private 
    def sub_params
        params.require(:sub).permit(:title,:description)
    end
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController


    def new 
        @user = User.new.decorate 
    end

    def create 

        @user=User.new(user_params).decorate
        if @user.save 
            flash[:notices] = ['Successful Login']
            login!(@user)
            redirect_to subs_url 
        else
            flash.now[:errors] = @user.errors.full_messages 
            @user= User.new(username: params[:user][:username]).decorate
            render :new
        end
    end

    
    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
    def auth_token 
        "<input 
        type='hidden'
        name='authenticity_token'
        value='#{form_authenticity_token}'>".html_safe 
    end
end

reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/helpers/user_helper.rb
module UserHelper
end

reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

reddit_clone/app/views/shared/_form.html.erb
<form action="<%=user.form_url(url_method)%>" method="POST">
    <%=auth_token %>
    <label for='User'>Username</label>
    <input type='text' id='User' name='user[username]' value="<%=user.username%>">
    <br>
    <br>
    <label for='pass'>Password</label>
    <input type='password' id='pass' name='user[password]' value="">
    <br>
    <br>
    <input type='submit' value="<%=user.submit_form(url_method)%>">

</form>

reddit_clone/app/views/subs/_form.html.erb
<form action="<%=sub.form_url%>" method="POST">
    <%=auth_token %>
    <input type='hidden' name='_method' value="<%=sub.form_method%>">

    <label>title
        <input type='text' name='sub[title]' value="<%=sub.title%>">
    </label>
    <label>description
        <textarea name='sub[description]'><%=sub.description%></textarea>
    </label>
    <button><%=sub.submit_form%></button>
</form>

reddit_clone/app/views/subs/edit.html.erb
<%= render 'form', sub: @sub %>

reddit_clone/app/views/subs/index.html.erb
<%@subs.each do |sub|%>

    <%= link_to sub.title, sub_url(id: sub.id)%>
    <%end %>

reddit_clone/app/views/subs/new.html.erb
<%= render 'form', sub: @sub%>

reddit_clone/app/views/subs/show.html.erb
<%=link_to "ALL SUBS", subs_url %>
<br>
<br>
<br>
<br>
<%=link_to "Make a Post", new_sub_post_url(sub_id: @sub.id) %>
<br>
<% @sub.posts.each do |post| %>
    <%=link_to post.title, post_url(id: post.id) %>
    <br>
    <br>
<% end %>

reddit_clone/app/views/users/new.html.erb
<%= render "shared/form", user: @user, url_method: 'create' %>